blank_issues_enabled: false
contact_links:
  - name: Dev Support
    url: mailto:asylum.defi@pm.me
    about: If you need support or have questions, please contact the developer.
  - name: GitBook
    url: https://asylum-labs.gitbook.io/asylum/
 about: Learn more about Asylum Labs
  - name: Warpcast
    url: https://warpcast.com/asylum-labs
    about: Contact us on Warpcast
  - name: Twitter
    url: https://twitter.com/asylum-labs
    about: Contact us on Twitter
  - name: Paragraph
    url: https://paragraph.xyz/asylum-labs
    about: Stay up to date with the Asylum Labs newsletter