[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
viaIR = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v2-core/=lib/uniswap/v2-core/",
    "@uniswap/v3-core/=lib/uniswap/v3-core/",
    "@uniswap/v3-periphery/=lib/uniswap/v3-periphery/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options