# when `main` is updated, sync to `deploy/fleek`
# due to current fleek build requirements
# it is necessary to keep the branches separate
name: Sync Main to Deploy/Fleek

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Checkout deploy/fleek branch
        run: git checkout -B deploy/fleek origin/deploy/fleek

      - name: Merge main into deploy/fleek
        run: git merge origin/main --no-ff

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin deploy/fleek
