name: Update Changelog

on:
  pull_request:
    types: [closed]

jobs:
  update-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run changelog script
        run: npm run changelog

      - name: Commit changes
        run: |
          git config --local user.name "Xamie"
          git config --local user.email "xamie-xeon@github.com"
          git add .
          git commit -m "ci: update changelog"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
